### ISSUE TITLE
concurrent map read/write error

### ISSUE THREAD

**Issue by jgangemi** [srevinsaju/togomak#24]
```INFO[0001] [stage=deploy] WARN [stage=version] Warning: In a future version of Poetry, PyPI will be disabled automatically if at least one custom source is configured with another priority than 'explicit'. In order to avoid a breaking change and make your pyproject.toml forward compatible, add PyPI explicitly via 'poetry source add pypi'. By the way, this has the advantage that you can set the priority of PyPI as with any other source.
WARN[0001] [stage=deploy] fatal error: concurrent map read and map write
INFO[0001] [stage=deploy] INFO [+] init
WARN[0001] [stage=deploy] 
WARN[0001] [stage=deploy] goroutine 69 [running]:
WARN[0001] [stage=deploy] github.com/hashicorp/hcl/v2.Traversal.TraverseAbs({0xc000520780?, 0x14c2ec8?, 0xc0000440e5?}, 0xc00050f8f0)
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.17.0/traversal.go:82 +0x2c5
WARN[0001] [stage=deploy] github.com/hashicorp/hcl/v2/hclsyntax.(*ScopeTraversalExpr).Value(0xc0010c19e0, 0xc00050f8f0)
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.17.0/hclsyntax/expression.go:139 +0x3b
WARN[0001] [stage=deploy] github.com/srevinsaju/togomak/v1/pkg/blocks/data.(*EnvProvider).DecodeBody(0xc00056a900, {0x14c24b8, 0xc0010d86e0})
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/blocks/data/env.go:98 +0x2fb
WARN[0001] [stage=deploy] github.com/srevinsaju/togomak/v1/pkg/ci.Data.Run({{0xc00104c424, 0x3}, {0xc00104c427, 0x3}, {0x0, 0x0}, {0x0, 0x0}, {0x14c24b8, 0xc0010d86e0}}, ...)
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/ci/data_run.go:43 +0x30a
WARN[0001] [stage=deploy] github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra.func1({0xc0010df030, 0xc})
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:306 +0xce
WARN[0001] [stage=deploy] created by github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:305 +0x1f3e
WARN[0001] [stage=deploy] 
WARN[0001] [stage=deploy] goroutine 1 [semacquire]:
WARN[0001] [stage=deploy] sync.runtime_Semacquire(0xc000568380?)
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/sema.go:62 +0x27
WARN[0001] [stage=deploy] sync.(*WaitGroup).Wait(0xc0000ca180?)
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/sync/waitgroup.go:116 +0x4b
WARN[0001] [stage=deploy] github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra({{0xc00003c274, 0x21}, {0x7fffbe2313d2, 0x21}, 0x1, 0x1, 0x1, {0x7fffbe23145d, 0x6}, {0x0, ...}, ...})
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:380 +0x15b3
WARN[0001] [stage=deploy] main.run(0xc0000c9340?)
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/cmd/togomak/main.go:211 +0x98
WARN[0001] [stage=deploy] github.com/urfave/cli/v2.(*Command).Run(0xc0000c9340, 0xc0002e7cc0, {0xc0000340a0, 0xa, 0xa})
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.5/command.go:274 +0x9eb
WARN[0001] [stage=deploy] github.com/urfave/cli/v2.(*App).RunContext(0xc000fea1e0, {0x14c22f8?, 0xc000044088}, {0xc0000340a0, 0xa, 0xa})
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.5/app.go:332 +0x616
WARN[0001] [stage=deploy] github.com/urfave/cli/v2.(*App).Run(...)
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.5/app.go:309
WARN[0001] [stage=deploy] main.main()
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/cmd/togomak/main.go:142 +0x118f
WARN[0001] [stage=deploy] 
WARN[0001] [stage=deploy] goroutine 6 [select]:
WARN[0001] [stage=deploy] code.gitea.io/gitea/modules/log.(*ChannelledLog).Start(0xc0002b96c0)
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/code.gitea.io/gitea@v1.19.3/modules/log/event.go:79 +0xd6
WARN[0001] [stage=deploy] created by code.gitea.io/gitea/modules/log.NewChannelledLog
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/code.gitea.io/gitea@v1.19.3/modules/log/event.go:68 +0x385
WARN[0001] [stage=deploy] 
WARN[0001] [stage=deploy] goroutine 7 [select]:
WARN[0001] [stage=deploy] code.gitea.io/gitea/modules/log.(*MultiChannelledLog).Start(0xc0000d4120)
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/code.gitea.io/gitea@v1.19.3/modules/log/event.go:340 +0x2bc
WARN[0001] [stage=deploy] created by code.gitea.io/gitea/modules/log.(*MultiChannelledLog).AddLogger
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/code.gitea.io/gitea@v1.19.3/modules/log/event.go:221 +0x176
WARN[0001] [stage=deploy] 
WARN[0001] [stage=deploy] goroutine 18 [syscall]:
WARN[0001] [stage=deploy] os/signal.signal_recv()
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/sigqueue.go:152 +0x2f
WARN[0001] [stage=deploy] os/signal.loop()
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/os/signal/signal_unix.go:23 +0x19
WARN[0001] [stage=deploy] created by os/signal.Notify.func1.1
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/os/signal/signal.go:151 +0x2a
WARN[0001] [stage=deploy] 
WARN[0001] [stage=deploy] goroutine 33 [select]:
WARN[0001] [stage=deploy] github.com/srevinsaju/togomak/v1/pkg/orchestra.InterruptHandler({0x14c2368, 0xc0010e2fc0}, 0xc001048c40, 0xc0010ea4e0, 0xc000011170)
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/orchestra/interrupt.go:16 +0xe5
WARN[0001] [stage=deploy] created by github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:180 +0x101d
WARN[0001] [stage=deploy] 
WARN[0001] [stage=deploy] goroutine 34 [select]:
WARN[0001] [stage=deploy] github.com/srevinsaju/togomak/v1/pkg/orchestra.KillHandler({0x14c2368, 0xc0010e2fc0}, 0xc001048c40, 0xc0010ea540, 0xc000011170)
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/orchestra/interrupt.go:56 +0xe5
WARN[0001] [stage=deploy] created by github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:181 +0x10e5
WARN[0001] [stage=deploy] 
WARN[0001] [stage=deploy] goroutine 35 [chan receive]:
WARN[0001] [stage=deploy] github.com/srevinsaju/togomak/v1/pkg/orchestra.daemonKiller({0x14c2368, 0xc0010e2fc0}, 0x0?, 0xc000011188)
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:433 +0x1c5
WARN[0001] [stage=deploy] created by github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:182 +0x118d
WARN[0001] [stage=deploy] 
WARN[0001] [stage=deploy] goroutine 67 [runnable]:
WARN[0001] [stage=deploy] github.com/hashicorp/hcl/v2/hclsyntax.Variables.func1({0xc000520640?, 0x4?, 0x4?})
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.17.0/hclsyntax/variables.go:18 +0xec
WARN[0001] [stage=deploy] github.com/hashicorp/hcl/v2/hclsyntax.(*variablesWalker).Enter(0xc0002c5200, {0x14bebb0?, 0xc0010c1200?})
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.17.0/hclsyntax/variables.go:51 +0x277
WARN[0001] [stage=deploy] github.com/hashicorp/hcl/v2/hclsyntax.Walk({0x14bebb0, 0xc0010c1200}, {0x14bebd8, 0xc0002c5200})
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.17.0/hclsyntax/walk.go:37 +0x5d
WARN[0001] [stage=deploy] github.com/hashicorp/hcl/v2/hclsyntax.Variables({0x14c38c0?, 0xc0010c1200})
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.17.0/hclsyntax/variables.go:23 +0xcc
WARN[0001] [stage=deploy] github.com/hashicorp/hcl/v2/hclsyntax.(*ScopeTraversalExpr).Variables(0xc001103460?)
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.17.0/hclsyntax/expression_vars.go:54 +0x25
WARN[0001] [stage=deploy] github.com/srevinsaju/togomak/v1/pkg/blocks/data.Variables({0x14c6280, 0xc0010ebb00}, {0x14c24b8, 0xc0010d8630})
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/blocks/data/provider.go:36 +0x17f
WARN[0001] [stage=deploy] github.com/srevinsaju/togomak/v1/pkg/ci.Data.Variables({{0xc00104c3f4, 0x3}, {0xc00104c3f8, 0x6}, {0x0, 0x0}, {0x0, 0x0}, {0x14c24b8, 0xc0010d8630}})
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/ci/data_hcl.go:16 +0xf9
WARN[0001] [stage=deploy] github.com/srevinsaju/togomak/v1/pkg/ci.Data.Run({{0xc00104c3f4, 0x3}, {0xc00104c3f8, 0x6}, {0x0, 0x0}, {0x0, 0x0}, {0x14c24b8, 0xc0010d8630}}, ...)
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/ci/data_run.go:90 +0xef8
WARN[0001] [stage=deploy] github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra.func1({0xc0010df130, 0xf})
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:306 +0xce
WARN[0001] [stage=deploy] created by github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:305 +0x1f3e
WARN[0001] [stage=deploy] 
WARN[0001] [stage=deploy] goroutine 42 [select]:
WARN[0001] [stage=deploy] io.(*pipe).read(0xc00056a360, {0xc00119c000, 0x10000, 0x4215c5?})
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/io/pipe.go:57 +0xb1
WARN[0001] [stage=deploy] io.(*PipeReader).Read(0x2085b10?, {0xc00119c000?, 0xc000578000?, 0x1000000014c2368?})
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/io/pipe.go:136 +0x25
WARN[0001] [stage=deploy] bufio.(*Scanner).Scan(0xc00016cf28)
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/bufio/scan.go:214 +0x876
WARN[0001] [stage=deploy] github.com/sirupsen/logrus.(*Entry).writerScanner(0xdfe88e?, 0xc000570020, 0xc0005662d0)
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/github.com/srevinsaju/logrus@v1.10.2-0.20230616201049-4e5a7636a82f/writer.go:79 +0x11f
WARN[0001] [stage=deploy] created by github.com/sirupsen/logrus.(*Entry).WriterLevel
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/github.com/srevinsaju/logrus@v1.10.2-0.20230616201049-4e5a7636a82f/writer.go:52 +0x3d1
WARN[0001] [stage=deploy] 
WARN[0001] [stage=deploy] goroutine 43 [select]:
WARN[0001] [stage=deploy] io.(*pipe).read(0xc00056a3c0, {0xc00122e189, 0xfe77, 0x14bf650?})
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/io/pipe.go:57 +0xb1
WARN[0001] [stage=deploy] io.(*PipeReader).Read(0x0?, {0xc00122e189?, 0xc000552c90?, 0xc000578480?})
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/io/pipe.go:136 +0x25
WARN[0001] [stage=deploy] bufio.(*Scanner).Scan(0xc001101f28)
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/bufio/scan.go:214 +0x876
WARN[0001] [stage=deploy] github.com/sirupsen/logrus.(*Entry).writerScanner(0x0?, 0xc000570030, 0xc0005662e0)
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/github.com/srevinsaju/logrus@v1.10.2-0.20230616201049-4e5a7636a82f/writer.go:79 +0x11f
WARN[0001] [stage=deploy] created by github.com/sirupsen/logrus.(*Entry).WriterLevel
WARN[0001] [stage=deploy] 	/home/runner/go/pkg/mod/github.com/srevinsaju/logrus@v1.10.2-0.20230616201049-4e5a7636a82f/writer.go:52 +0x3d1
WARN[0001] [stage=deploy] 
WARN[0001] [stage=deploy] goroutine 68 [runnable]:
WARN[0001] [stage=deploy] syscall.Syscall6(0xc001224558?, 0x14?, 0x7fb60655ff08?, 0x7fb62db14f18?, 0xd0?, 0xc000076c00?, 0xc001213450?)
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/syscall/syscall_linux.go:91 +0x36
WARN[0001] [stage=deploy] syscall.fstatat(0x0?, {0xc001224558?, 0x14?}, 0xc001213488, 0x0?)
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/syscall/zsyscall_linux_amd64.go:1443 +0x9a
WARN[0001] [stage=deploy] syscall.Stat(...)
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/syscall/syscall_linux_amd64.go:66
WARN[0001] [stage=deploy] os.statNolog.func1(...)
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/os/stat_unix.go:32
WARN[0001] [stage=deploy] os.ignoringEINTR(...)
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/os/file_posix.go:245
WARN[0001] [stage=deploy] os.statNolog({0xc001224558, 0x14})
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/os/stat_unix.go:31 +0x58
WARN[0001] [stage=deploy] os.Stat({0xc001224558, 0x14})
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/os/stat.go:13 +0x34
WARN[0001] [stage=deploy] os/exec.findExecutable({0xc001224558, 0x14})
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/os/exec/lp_unix.go:23 +0x27
WARN[0001] [stage=deploy] os/exec.LookPath({0xfc1893, 0x4})
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/os/exec/lp_unix.go:71 +0x205
WARN[0001] [stage=deploy] os/exec.Command({0xfc1893, 0x4}, {0xc00120b380, 0x3, 0xc?})
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/os/exec/exec.go:419 +0x225
WARN[0001] [stage=deploy] os/exec.CommandContext({0x14c2368, 0xc0010e2fc0}, {0xfc1893?, 0x0?}, {0xc00120b380?, 0x419871?, 0x208d740?})
WARN[0001] [stage=deploy] 	/opt/hostedtoolcache/go/1.20.5/x64/src/os/exec/exec.go:446 +0x53
WARN[0001] [stage=deploy] github.com/srevinsaju/togomak/v1/pkg/ci.(*Stage).Run(0xc000578b40, {0x14c2368, 0xc0010e2fc0})
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/ci/stage_run.go:378 +0x1fa5
WARN[0001] [stage=deploy] github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra.func1({0xc0010df1b0, 0xa})
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:306 +0xce
WARN[0001] [stage=deploy] created by github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra
WARN[0001] [stage=deploy] 	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:305 +0x1f3e
ERRO[0001] <nil>: failed to run command (stage.deploy); exit status 2```

**Comment by srevinsaju** [comment]
I am not able to reproduce this, I will need a script file where I can reproduce this, does this happen randomly?

**Comment by jgangemi** [comment]
```togomak root +build        
INFO[0000] togomak (version=1.2.2)
INFO[0000] [provider=git] Still pulling git repo data.git... [0s elapsed]
INFO[0001] [provider=git] Completed pulling git repo data.git in [2s elapsed]
fatal error: concurrent map read and map write

goroutine 108 [running]:
github.com/srevinsaju/togomak/v1/pkg/ci.(*Macro).Run(0xc0005a4a20, {0x20d0608, 0xc0014ee6c0})
	/home/runner/work/togomak/togomak/pkg/ci/macro_run.go:30 +0x1ee
github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra.func1({0xc0014e30c0, 0xa})
	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:306 +0xce
created by github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra
	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:305 +0x1f3e

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0005b65e0?)
	/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0xc0005bc240?)
	/opt/hostedtoolcache/go/1.20.7/x64/src/sync/waitgroup.go:116 +0x4b
github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra({{0xc000040054, 0x3d}, {0x0, 0x0}, 0x0, 0x0, 0x0, {0x0, 0x0}, {0x0, ...}, ...})
	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:380 +0x15b3
main.run(0xc00145fd88?)
	/home/runner/work/togomak/togomak/cmd/togomak/main.go:211 +0x98
github.com/urfave/cli/v2.(*Command).Run(0xc00015f340, 0xc0002a48c0, {0xc00011c180, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.5/command.go:274 +0x9eb
github.com/urfave/cli/v2.(*App).RunContext(0xc0011c25a0, {0x20d0598?, 0xc00012a018}, {0xc00011c180, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.5/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.5/app.go:309
main.main()
	/home/runner/work/togomak/togomak/cmd/togomak/main.go:142 +0x118f

goroutine 19 [select]:
code.gitea.io/gitea/modules/log.(*ChannelledLog).Start(0xc0002d56c0)
	/home/runner/go/pkg/mod/code.gitea.io/gitea@v1.19.3/modules/log/event.go:79 +0xd6
created by code.gitea.io/gitea/modules/log.NewChannelledLog
	/home/runner/go/pkg/mod/code.gitea.io/gitea@v1.19.3/modules/log/event.go:68 +0x385

goroutine 20 [select]:
code.gitea.io/gitea/modules/log.(*MultiChannelledLog).Start(0xc00016a120)
	/home/runner/go/pkg/mod/code.gitea.io/gitea@v1.19.3/modules/log/event.go:340 +0x2bc
created by code.gitea.io/gitea/modules/log.(*MultiChannelledLog).AddLogger
	/home/runner/go/pkg/mod/code.gitea.io/gitea@v1.19.3/modules/log/event.go:221 +0x176

goroutine 49 [syscall]:
os/signal.signal_recv()
	/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/sigqueue.go:149 +0x28
os/signal.loop()
	/opt/hostedtoolcache/go/1.20.7/x64/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	/opt/hostedtoolcache/go/1.20.7/x64/src/os/signal/signal.go:151 +0x2a

goroutine 28 [select]:
github.com/srevinsaju/togomak/v1/pkg/orchestra.InterruptHandler({0x20d0608, 0xc0014ee6c0}, 0xc00148fe10, 0xc0014df500, 0xc000011638)
	/home/runner/work/togomak/togomak/pkg/orchestra/interrupt.go:16 +0xe5
created by github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra
	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:180 +0x101d

goroutine 29 [select]:
github.com/srevinsaju/togomak/v1/pkg/orchestra.KillHandler({0x20d0608, 0xc0014ee6c0}, 0xc00148fe10, 0xc0014df560, 0xc000011638)
	/home/runner/work/togomak/togomak/pkg/orchestra/interrupt.go:56 +0xe5
created by github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra
	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:181 +0x10e5

goroutine 30 [chan receive]:
github.com/srevinsaju/togomak/v1/pkg/orchestra.daemonKiller({0x20d0608, 0xc0014ee6c0}, 0x0?, 0xc000011650)
	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:433 +0x1c5
created by github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra
	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:182 +0x118d

goroutine 107 [runnable]:
golang.org/x/text/unicode/norm.Form.String(0x0?, {0xc0013221e0?, 0x9?})
	/home/runner/go/pkg/mod/golang.org/x/text@v0.9.0/unicode/norm/normalize.go:59 +0x285
github.com/zclconf/go-cty/cty/ctystrings.Normalize(...)
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.13.0/cty/ctystrings/normalize.go:13
github.com/zclconf/go-cty/cty.NormalizeString(...)
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.13.0/cty/value_init.go:109
github.com/zclconf/go-cty/cty.StringVal(...)
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.13.0/cty/value_init.go:99
github.com/hashicorp/hcl/v2/hclsyntax.(*TemplateExpr).Value(0xc00009b440, 0xc000010708)
	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.17.0/hclsyntax/expression_template.go:101 +0x674
github.com/hashicorp/hcl/v2/hclsyntax.(*ObjectConsKeyExpr).Value(0xc0000107c8?, 0x10159f0?)
	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.17.0/hclsyntax/expression.go:1209 +0x27f
github.com/hashicorp/hcl/v2/hclsyntax.(*ObjectConsExpr).Value(0xc00118e5a0, 0xc000010708)
	/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.17.0/hclsyntax/expression.go:1079 +0x19e
github.com/srevinsaju/togomak/v1/pkg/ci.(*Macro).Run(0xc0005a4960, {0x20d0608, 0xc0014ee6c0})
	/home/runner/work/togomak/togomak/pkg/ci/macro_run.go:39 +0x2c8
github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra.func1({0xc0014e30a0, 0xb})
	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:306 +0xce
created by github.com/srevinsaju/togomak/v1/pkg/orchestra.Orchestra
	/home/runner/work/togomak/togomak/pkg/orchestra/orchestra.go:305 +0x1f3e
```
